version: "3"
services:
  simplified-calendar-postgres:
    container_name: simplified-calendar-db
    image: postgres
    environment:
      POSTGRES_DB: simplified-calendar
      POSTGRES_USER: simplified-calendar
      POSTGRES_PASSWORD: utDem3uFz2P4L!QF
      PGDATA: /data/postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/simplified-calendar/data"
    ports:
      - 5432:5432