## default connection pool
spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
    time-zone: America/Sao_Paulo
    serialization:
      write_dates_as_timestamps: false
      FAIL_ON_EMPTY_BEANS: false

datasource:
  host: localhost
  port: 5432
  database: simplified-calendar
  username: simplified-calendar
  password: utDem3uFz2P4L!QF